# Header
nav:
  首页: /archives
  # Categories: /category
  标签: /tag

# favicon
favicon: /favicon.ico

# logo. You should provide a dark and a light version for the image, e.g. fish-white.svg, fish-black.svg
logo: /img/fish-bone
title_logo: /img/torpedo-missile

# links
links:
  Github: https://github.com/douglasyu
  # ZhiHu:
  # Twitter:
  # Weibo:

# analytics
google_analytics:
baidu_analytics:

# mathjax
fancybox: true

# mathjax
mathjax: true

# echarts
echarts: true

# busuanzi
busuanzi: true

# mermaid
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme: default

# giscus
giscus:
  enable: false
  repo:
  repo_id:
  category:
  category_id:
  mapping:

# comment-cusdis
cusdis:
  app_id: b1abaae5-e037-4ce7-b3ae-b7196fa8f235

# maple
maple:
  enable: true
  # fall leaf count
  count: 10
  # 0-1
  speed: 0.5

